name: dating_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  animations: ^2.0.1
  carousel_slider: ^4.0.0
  cloud_firestore: ^2.5.1
  country_pickers: ^2.0.0
  cupertino_icons: ^1.0.2
  email_validator: ^2.0.1
  equatable: ^2.0.3
  firebase_auth: ^3.1.0
  firebase_core: ^1.6.0
  firebase_storage: ^10.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_datetime_picker:
    git: https://github.com/Realank/flutter_datetime_picker.git
  flutter_screenutil: ^5.0.0+2
  geocoding: ^2.0.1
  geolocator: ^7.6.0
  http: ^0.13.3
  image_picker: ^0.8.4
  mime: ^1.0.0
  path_provider: ^2.0.3
  persistent_bottom_nav_bar: ^4.0.2
  pin_code_fields: ^7.3.0
  shared_preferences: ^2.0.7
  sms_autofill: ^2.0.1
  tcard: ^1.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/images/search_friends/
    - assets/images/sample_images/
    - assets/images/enable_notification/
  uses-material-design: true
  fonts:
    - family: Modernist
      fonts:
        - asset: assets/font/Sk-Modernist-Regular.otf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
