name: dating_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  animations: ^2.0.1
  bubble: ^1.2.1
  carousel_slider: ^4.0.0
  cloud_firestore: ^2.5.1
  country_pickers: ^2.0.0
  cupertino_icons: ^1.0.2
  email_validator: ^2.0.1
  firebase_messaging: ^10.0.6
  flick_video_player: ^0.3.1
  equatable: ^2.0.3
  firebase_auth: ^3.1.0
  firebase_core: ^1.6.0
  firebase_storage: ^10.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  flutter_datetime_picker:
    git: https://github.com/Realank/flutter_datetime_picker.git
  flutter_screenutil: ^5.0.0+2
  flutter_linkify: ^5.0.2
  geocoding: ^2.0.1
  geolocator: ^7.7.1
  http: ^0.13.3
  image_picker: ^0.8.4
  mime: ^1.0.0
  multi_image_picker2: ^5.0.2
  path_provider: ^2.0.3
  persistent_bottom_nav_bar: ^4.0.2
  provider: ^5.0.0
  pin_code_fields: ^7.3.0
  shared_preferences: ^2.0.7
  sms_autofill: ^2.0.1
  url_launcher: ^6.0.10
  tcard: ^1.3.5
  cached_network_image: ^3.1.0
  emoji_picker_flutter: ^1.0.7
  flutter_local_notifications: ^8.2.0
  clipboard: ^0.1.3
  video_thumbnail: ^0.4.3
  giphy_picker: ^2.0.0
  youtube_player_flutter: ^8.0.0
  flutter_sound: ^8.3.9
  permission_handler: ^8.2.5
  file_picker: ^4.1.4
  audioplayers: ^0.20.1

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/images/search_friends/
    - assets/images/sample_images/
    - assets/images/enable_notification/
  uses-material-design: true
  fonts:
    - family: Modernist
      fonts:
        - asset: assets/font/Sk-Modernist-Regular.otf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
